2016-05-18 17:08:41,265 [9] INFO  Crawler.Logger - 系统初始化Logger模块
2016-05-18 17:08:56,354 [9] ERROR Crawler.DataService.DBInit - 初始化数据库InitCategoryTable失败
System.Data.SqlClient.SqlException (0x80131904): 无法打开登录所请求的数据库 "mvc5_20160420"。登录失败。
用户 'sa' 登录失败。
   在 System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling)
   在 System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   在 System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   在 System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   在 System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 Crawler.DataService.SqlHelper.ExecuteNonQuery(String sql) 位置 e:\online5\20160518Advanced5Course28Collection\Crawler\DataService\SqlHelper.cs:行号 26
   在 Crawler.DataService.DBInit.InitCategoryTable() 位置 e:\online5\20160518Advanced5Course28Collection\Crawler\DataService\DBInit.cs:行号 84
ClientConnectionId:0d8979cd-0550-4bf5-ab0f-cfdb724abc9e
Error Number:4060,State:1,Class:11
2016-05-18 17:08:56,385 [9] ERROR Crawler.Program - 异常啦，
System.Data.SqlClient.SqlException (0x80131904): 无法打开登录所请求的数据库 "mvc5_20160420"。登录失败。
用户 'sa' 登录失败。
   在 Crawler.DataService.DBInit.InitCategoryTable() 位置 e:\online5\20160518Advanced5Course28Collection\Crawler\DataService\DBInit.cs:行号 95
   在 Crawler.Program.Main(String[] args) 位置 e:\online5\20160518Advanced5Course28Collection\Crawler\Program.cs:行号 39
ClientConnectionId:0d8979cd-0550-4bf5-ab0f-cfdb724abc9e
Error Number:4060,State:1,Class:11
2016-05-18 17:09:29,572 [7] INFO  Crawler.Logger - 系统初始化Logger模块
2016-05-18 17:10:32,879 [9] INFO  Crawler.Logger - 系统初始化Logger模块
2016-05-18 20:19:54,410 [9] INFO  Crawler.Logger - 系统初始化Logger模块
